import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import "./globals.css";
import { DrawerProvider } from "@/shared/contexts/DrawerContext";
import NextAuthSessionProvider from "@/providers/sessionProvider";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Gestão de Pedidos Luvep",
    description: "Generated by create next app"
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="pt-br">
            <body className={nunito.className}>
                <NextAuthSessionProvider>
                    <DrawerProvider>
                        {children}
                    </DrawerProvider>
                </NextAuthSessionProvider>
            </body>
        </html>
    );
}